### ISSUE TITLE
Support Love v11

### ISSUE THREAD

**Issue by john-cheesman** [excessive/patchy#8]
https://github.com/excessive/patchy/blob/733ce9608a3e0a092ac6b4edcf8730f44ee25ad7/patchy.lua#L344

`Image:getData()` was dropped in v11.0, I'm not sure what the alternative is for this.

**Comment by shakesoda** [comment]
I will look into this

**Comment by pablomayobre** [comment]
It's not as simple... I ported my fork to 11.x https://github.com/excessive/patchy/compare/master...Positive07:master (I cleaned up the whitespace so the comparison looks horrible, better check the individual commits)

But honestly I don't think some things are as good with this library, I believe it could make use of auto-batching introduced in 11.x for example and the Image loading should probably be part of it instead of taking it as input in some functions... So a rewrite (or new library) specifically targeting 11.x may be a good idea

**Comment by shakesoda** [comment]
argh, the spacing change makes the diff absolutely useless.

edit: individual revs are ok, as you said. without the spacing changes I'd be happy to merge an update.

**Comment by pablomayobre** [comment]
Hahaha I didn't care since I forked... wasn't thinking about PRing... my current idea would be a rewrite using patchy as base

But feel free to somehow make the same changes and push them? Or wait till I get to it which may be an eternity honestly haha I have other current projects sorry

PS: Honestly I would merge the spacing changes too, it was all over the place when I checked, tabs and spaces mixed in, spaces where there shouldn't be... if it looks on github it may be for sheer luck

**Comment by shakesoda** [comment]
spacing looks mostly fine to me, there's just a couple lines where someone screwed up and used tabs to align some ='s instead of only using them for indents

**Comment by john-cheesman** [comment]
@Positive07 I tried your version and it works great, only thing I had to change was passing a string instead of the actual image. I'm using the [cargo asset loader](https://github.com/bjornbytes/cargo) so it would great if I could still pass the image but not sure if this would be possible with the changes to `ImageData` in v11.

**Comment by pablomayobre** [comment]
You need an ImageData, Images won't work since you can't get the ImageData from it anymore and of course you need to read the pixels of the ImageData to determine the patch lines.

You could try to add a loader to cargo along the lines of:
```lua
local patchy = require "patchy"
local cargo  = require "cargo"

local assets = cargo.init({
  loaders = {
    ["9.png"] = patchy.load
  },
})
```
I haven't tested if this works... but I believe it should, you'll need to name your 9-patch images like `window.9.png`

**Comment by john-cheesman** [comment]
This works really well, never thought of using patchy directly as a cargo loader. Thanks for your help.

**Comment by pablomayobre** [comment]
Glad I could help you, and I agree that the design of cargo is so good allowing you to do this stuff so easily

**Comment by VickyPhoton** [comment]
@Positive07 @shakesoda  So I assume the PR was still not merged? Because as of love v11.2 this still doesnt work and the getData() code is still present.

**Comment by pablomayobre** [comment]
There is no PR, I don't intend on making one, I changed a bunch of stuff, and autofixed spacing to fit my needs so the changelog looks horrible.

Feel free to use my port if you want, but honestly I don't think this is a good way to approach 9-patch anymore. Given that LÖVE has autobatching since 11.0 which would theoretically allow to batch several uses of a single 9-patch pattern into one draw call (if used correctly) instead of batching a single use of the patch into a single draw call (which was an amazing reduction from 9+ draw calls per patch use, back when autobatching wasn't a thing)

So yeah I'd like to make a new library, if there is enough interest I might consider it

**Comment by shakesoda** [comment]
@Positive07 i pulled your changes back, thanks a bunch for taking care of it.

i agree this isn't the optimal way to draw lots of patches, but at the same time in practice i have few enough that it's just not a bottleneck.

closing
